CREATE TABLE wastewater_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    country TEXT NOT NULL,
    year INTEGER NOT NULL,
    POP FLOAT,
    POP_WATON_PCT FLOAT,
    POP_WATOFF_PCT FLOAT,
    USE_WATON_AVG FLOAT,
    USE_WATOFF_AVG FLOAT,
    USE_VOL FLOAT,
    USE_TO_WW_PCT FLOAT,
    GEN_VOL FLOAT,
    SEW_PCT FLOAT,
    SEP_PCT FLOAT,
    OTHIMP_PCT FLOAT,
    UNIMP_PCT FLOAT,
    OD_PCT FLOAT,
    SEW_VOL FLOAT,
    SEP_VOL FLOAT,
    OTHIMP_VOL FLOAT,
    UNIMP_VOL FLOAT,
    OD_VOL FLOAT,
    SEW_DEL_WWTP_PCT FLOAT,
    SEW_ST_WWTP_CMP_PCT FLOAT,
    SEW_ST_WWTP_TCH_PCT FLOAT,
    SEP_CONT_PCT FLOAT,
    SEP_ON_BUR_PCT FLOAT,
    SEP_LOCAL_PCT FLOAT,
    SEP_OFF_EMPT_PCT FLOAT,
    SEP_ON_NOEMPT_PCT FLOAT,
    SEP_OFF_DEL_WWTP_PCT FLOAT,
    SEP_OFF_ST_WWTP_PCT FLOAT,
    SEW_DEL_TRT_VOL FLOAT,
    SEP_OFF_DEL_TRT_VOL FLOAT,
    SEP_ON_DEL_TRT_VOL FLOAT,
    DEL_TRT_VOL FLOAT,
    SEW_STWW_VOL FLOAT,
    SEP_OFF_STWW_VOL FLOAT,
    SEP_ON_STWW_VOL FLOAT,
    STWW_VOL FLOAT,
    SEW_STWW_PCT FLOAT,
    SEP_OFF_STWW_PCT FLOAT,
    SEP_ON_STWW_PCT FLOAT,
    STWW_PCT FLOAT
);

-- Collumns in the table
SELECT sql
FROM sqlite_master
WHERE name = 'wastewater_data';

PRAGMA table_info(wastewater_data);

-- List all tables in the database
SELECT name 
FROM sqlite_master 
WHERE type = 'table';

`